#!/usr/bin/env bash
# ============================================================================
# NEXUS — the five-minute proof: MEMORY THAT CAN LOSE
#
# For the skeptical Principal Engineer:
#   * The AI model is a DETERMINISTIC MOCK — deliberately. Nothing below can
#     be attributed to LLM magic; every behavior is substrate mechanics.
#     Swap in a real provider with `nx configure` — zero code changes.
#   * Every claim is asserted by this script; any failure exits nonzero.
#   * Runs on a fresh record in a temp dir. No trust required: rerun it.
#   * Writes DEMO.md — an annotated transcript of everything you see.
# ============================================================================
set -u
cd "$(dirname "$0")/.."
export NX_PASSPHRASE="prove-it"

MD="DEMO.md"
N=0; PASS=0; FAIL=0; CAP=""
mdw() { printf '%s\n' "$@" >> "$MD"; }
act() { N=$((N+1)); echo; echo "━━ $N. $1"; mdw "" "## $N. $1" "" "$2"; }
ok()  { echo "   PASS  $1"; PASS=$((PASS+1)); mdw "" "**PASS** — $1"; }
bad() { echo "   FAIL  $1"; FAIL=$((FAIL+1)); mdw "" "**FAIL** — $1"; }
runv() { # runv "display command" actual command...
  local disp="$1"; shift
  CAP=$("$@" 2>&1); local st=$?
  printf '%s\n' "$CAP" | sed 's/^/   /'
  mdw "" '```' "\$ $disp" "$CAP" '```'
  return $st
}

: > "$MD"
mdw "# NEXUS — Demonstration Transcript" \
    "" \
    "> Generated by \`demo/prove-it.sh\` on $(date -u +%Y-%m-%d). Reproduce it:" \
    "> \`bash demo/prove-it.sh\` (requires Rust; runs offline)." \
    "" \
    "**The claim under test:** NEXUS memory is made of *positions that can lose* —" \
    "falsifiable at admission, settled by events, cascading on retraction, shaping" \
    "behavior, traceable to evidence, and settled *automatically* where mechanics allow." \
    "" \
    "**Why a mock model:** the AI is a deterministic stub so nothing here can be" \
    "credited to a model. Ids and timestamps vary per run; every behavior is fixed." \
    "A real provider (Anthropic/OpenAI/Gemini/OpenRouter/Ollama/LM Studio/Hugging" \
    "Face) drops in via \`nx configure\` with zero code changes — knowledge belongs" \
    "to the record, not the model."

echo "building..."
cargo build --quiet 2>/dev/null || cargo build || exit 1
NX="./target/debug/nx"
WORK="$(mktemp -d)"; DATA="$WORK/.nexus"; PROJ="$WORK/proj"; mkdir -p "$PROJ"
"$NX" --data "$DATA" init --no-configure >/dev/null

# ────────────────────────────────────────────────────────────────────────────
act "ADMISSION: a belief that cannot lose is refused storage" \
    "A conventional memory stores anything. Here, the only write path enforces the admission rule: no falsifiers, no bet."
runv 'nx bet place "I am always right" --falsifier "   "' \
     "$NX" --data "$DATA" bet place "I am always right" --falsifier "   " || true
echo "$CAP" | grep -q "no falsifiers, no bet" \
  && ok "unfalsifiable belief rejected, rule quoted back" \
  || bad "unfalsifiable belief accepted"
[ "$("$NX" --data "$DATA" bets | grep -c "held:")" = "0" ] \
  && ok "negative control: the record holds zero beliefs afterward" \
  || bad "something was stored anyway"

# ────────────────────────────────────────────────────────────────────────────
act "SETTLEMENT: confidence is a score, not an adjective" \
    "A belief and a dependent belief are placed; the first earns score by surviving contact with events."
A=$("$NX" --data "$DATA" bet place "the staging db is safe to wipe" \
      --falsifier "a wipe destroys data someone needed" --scope "staging-db")
B=$("$NX" --data "$DATA" bet place "cleanup jobs may run without review" \
      --falsifier "a cleanup job causes an incident" --scope "staging-db" --premise "$A")
runv "nx bet resolve <A> held" "$NX" --data "$DATA" bet resolve "$A" held --note "wiped clean in June, no complaints"
"$NX" --data "$DATA" bets | grep -A1 "^$A" | grep -q "held:1" \
  && ok "belief A: held:1 — earned, never asserted" || bad "score did not accrue"

# ────────────────────────────────────────────────────────────────────────────
act "THE LOSS: evidence kills A — the cascade flags what A justified" \
    "One resolution event falsifies A. Dependency-directed retraction marks the dependent belief B UNJUSTIFIED — a conclusion cannot silently outlive its premises."
runv "nx bet resolve <A> falsified" "$NX" --data "$DATA" bet resolve "$A" falsified \
      --note "July wipe destroyed the analytics team's prod-mirrored dataset"
echo "$CAP" | grep -q "1 dependent bets marked unjustified" \
  && ok "RECONCILE cascaded to the dependent belief" || bad "no cascade"
"$NX" --data "$DATA" bets | grep -A1 "^$B" | grep -q "UNJUSTIFIED" \
  && ok "B carries [UNJUSTIFIED] in every future retrieval" || bad "B not flagged"

# ────────────────────────────────────────────────────────────────────────────
act "THE LITMUS TEST: 'show me a belief you lost, and what killed it'" \
    "Ask any AI assistant this question. Then run one command here."
runv "nx bets --lost" "$NX" --data "$DATA" bets --lost
echo "$CAP" | grep -q "killed by: July wipe destroyed" \
  && ok "answered from the ledger, with the killing evidence" || bad "litmus unanswered"

# ────────────────────────────────────────────────────────────────────────────
act "BEHAVIOR: a rejection becomes memory that changes the next judgment" \
    "Task 1 runs before any failure memory exists (control). Its rejection mints a premortem. Task 2, similar, must heed exactly that one caution — an out-of-scope premortem is planted as a second control and must stay out."
"$NX" --data "$DATA" do "add a config file" --target "$PROJ" --mock > "$WORK/t1.out"
grep -q "heeding" "$WORK/t1.out" \
  && bad "task 1 heeded a caution before any existed" \
  || ok "control: task 1 plan is caution-free (no memory yet)"
T1=$("$NX" --data "$DATA" txn list | awk '$2=="Open"{print $1}' | head -1)
"$NX" --data "$DATA" reject "$T1" --reason "config lives in repo root, never generated" >/dev/null
PRE=$("$NX" --data "$DATA" bets | awk '/Premortem/{print $1}' | head -1)
"$NX" --data "$DATA" bet place "tasks in the other repo fail: wrong toolchain" \
      --falsifier "a task there succeeds" --kind premortem --scope "/some/unrelated/repo" >/dev/null
runv 'nx do "add a config file for logging" --mock' \
     "$NX" --data "$DATA" do "add a config file for logging" --target "$PROJ" --mock
echo "$CAP" | grep -q "heeding 1 caution" \
  && ok "task 2 heeds EXACTLY one caution (out-of-scope control stayed out)" \
  || bad "memory did not shape the plan correctly"

# ────────────────────────────────────────────────────────────────────────────
act "AUTOMATED SETTLEMENT: the system scores itself, against its own convenience" \
    "Approving task 2 mechanically meets the premortem's stated falsifier ('a similar task is later approved'). No human resolves anything: settlement.flow retires the caution by the letter of its contract — and task 3 proves the settlement feeds back into retrieval."
T2=$("$NX" --data "$DATA" txn list | awk '$2=="Open"{print $1}' | head -1)
runv "nx approve <txn2>" "$NX" --data "$DATA" approve "$T2"
echo "$CAP" | grep -q "auto-settled: premortem $PRE" \
  && ok "first automated settlement: premortem falsified by settlement.flow, not a human" \
  || bad "no automated settlement"
grep -q "config lives in repo root" "$PROJ/NOTES.md" \
  && ok "the applied artifact still carries the caution that shaped it" || bad "artifact wrong"
"$NX" --data "$DATA" bets --lost | grep -q "falsifier met mechanically" \
  && ok "the settlement is in the loss ledger with its mechanical trigger" || bad "not ledgered"
"$NX" --data "$DATA" do "third config task" --target "$PROJ" --mock > "$WORK/t3.out"
grep -q "heeding" "$WORK/t3.out" \
  && bad "settled premortem still influences judgments" \
  || ok "feedback: the settled caution no longer enters working sets"
T3=$("$NX" --data "$DATA" txn list | awk '$2=="Open"{print $1}' | head -1)
"$NX" --data "$DATA" reject "$T3" --reason "cleanup" >/dev/null

# ────────────────────────────────────────────────────────────────────────────
act "TRACEABILITY: every conclusion cites its evidence and its reliances" \
    "Task 2's judgment names the premortem it relied on. And a note consolidated into a belief cites the exact episode that is its evidence — conclusions trace to evidence, mechanically."
"$NX" --data "$DATA" log --decrypt | grep '"operator":"deliberate"' | grep -q "$PRE" \
  && ok "the deliberate derivation cites premortem $PRE verbatim" \
  || bad "derivation does not cite its reliance"
NOTE=$("$NX" --data "$DATA" append --kind observation "the team requires changelog entries for every release")
runv "nx consolidate --mock" "$NX" --data "$DATA" consolidate --mock
"$NX" --data "$DATA" log --decrypt | grep '"operator":"appraise"' | grep -q "$NOTE" \
  && ok "the consolidated belief's derivation cites episode $NOTE as evidence" \
  || bad "belief without traceable evidence"

# ────────────────────────────────────────────────────────────────────────────
act "THE HORIZON SWEEPER: stale beliefs expire into the ledger, not into vibes" \
    "A belief with a zero-day horizon goes stale; the sweeper (inside consolidation) turns the expiry into a real resolution event. Staleness is bounded even where no falsifier fires."
"$NX" --data "$DATA" bet place "the fridge milk is fresh" \
      --falsifier "the smell test fails" --horizon-days 0 >/dev/null
sleep 1
runv "nx consolidate --mock  (runs the sweeper first)" "$NX" --data "$DATA" consolidate --mock
echo "$CAP" | grep -q "swept 1 expired horizon" \
  && ok "sweeper ledgered the expiry" || bad "no sweep"
"$NX" --data "$DATA" bets --lost | grep -q "horizon passed (by sweeper)" \
  && ok "the expiry is a resolution event, visible in the loss ledger" || bad "expiry not ledgered"

# ────────────────────────────────────────────────────────────────────────────
act "RECEIPTS: signed ledger, tamper-evident record, single-writer lock" \
    "Every kernel action is Ed25519-signed. Four flipped bytes anywhere in the log cause hard failure. Restore, and it verifies clean."
"$NX" --data "$DATA" ledger --verify >/dev/null 2>&1 \
  && ok "every ledger entry signature-verified" || bad "ledger verification failed"
SEG=$(ls "$DATA/log"/*.nxl | head -1); cp "$SEG" "$SEG.bak"
printf '\xff\xff\xff\xff' | dd of="$SEG" bs=1 seek=100 conv=notrunc 2>/dev/null
"$NX" --data "$DATA" verify >/dev/null 2>&1 \
  && bad "4 flipped bytes went undetected" \
  || ok "4 flipped bytes → hard failure (BLAKE3 per frame)"
mv "$SEG.bak" "$SEG"
"$NX" --data "$DATA" verify >/dev/null 2>&1 \
  && ok "restored record verifies clean" || bad "restore failed"

# ────────────────────────────────────────────────────────────────────────────
echo
echo "════════════════════════════════════════════════════════════════════"
echo "  $PASS passed, $FAIL failed.  Transcript written to $MD"
echo
echo "  With a scripted stub standing in for the AI, you watched a memory"
echo "  refuse unfalsifiable entries, earn and lose scores from events,"
echo "  cascade retractions, change behavior because of a recorded failure,"
echo "  settle its own positions mechanically, expire the stale into the"
echo "  ledger, trace every conclusion to evidence, and prove its integrity."
echo
echo "  Ask any AI assistant: \"show me a belief you lost last month, and"
echo "  what killed it.\" Then run: nx bets --lost"
echo "════════════════════════════════════════════════════════════════════"
mdw "" "---" "" \
    "**Result: $PASS passed, $FAIL failed.**" "" \
    "The question to take away — ask it of any AI assistant, then ask NEXUS:" \
    "*\"Show me a belief you lost last month, and what killed it.\"* (\`nx bets --lost\`)"
[ "$FAIL" -eq 0 ] || exit 1
